version: '3'
services:
  app:
    image: wouterrutgers/group-ironmen
    volumes:
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: group_ironmen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./dbdata:/var/lib/mysql/
