[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
minfds=10000

[program:octane]
command=/usr/local/bin/octane.sh %(ENV_OCTANE_ARGUMENTS)s
directory=/app
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:schedule]
command=php artisan schedule:work
directory=/app
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:horizon]
command=php artisan horizon
directory=/app
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
