name: Dump game data

# To run locally: act --env GROUP_IRONMEN_PATH=$PWD -W .github/workflows/update-cache.yml -s GITHUB_TOKEN="$(gh auth token)" -P macos-latest=-self-hosted workflow_dispatch

on:
  workflow_dispatch:
  schedule:
    - cron: '47 * * * *'

jobs:
  cache:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 11

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: cache/runelite

      - run: |
          cache=$(curl -s https://archive.openrs2.org/caches.json | jq -r --arg cutoff "$(date -u -v-2H '+%Y-%m-%dT%H:%M:%SZ')" '
            [ .[] | select(.game == "oldschool" and .environment == "live" and .language == "en" and (.sources | contains(["Jagex"])) and .size != null) ] |
            map(select(.timestamp <= $cutoff)) |
            sort_by(.id) | last
          ')
          id=$(echo $cache | jq -r '.id')
          valid_keys=$(echo $cache | jq -r '.valid_keys')
          echo "CACHE_ID=$id" >> $GITHUB_ENV
          echo "VALID_KEYS=$valid_keys" >> $GITHUB_ENV

      - run: npm install
        working-directory: ./cache

      - run: npm install
        working-directory: ./

      - uses: actions/cache@v4
        id: cache
        with:
          path: cache/cache
          key: cache-${{ env.CACHE_ID }}-${{ env.VALID_KEYS }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: curl -o cache/cache/xteas.json https://archive.openrs2.org/caches/runescape/$CACHE_ID/keys.json

      - if: steps.cache.outputs.cache-hit != 'true'
        run: curl -o cache/cache/disk.zip https://archive.openrs2.org/caches/runescape/$CACHE_ID/disk.zip

      - if: steps.cache.outputs.cache-hit != 'true'
        run: unzip cache/cache/disk.zip -d cache/cache

      - run: npm run update
        working-directory: ./cache

      - run: node resources/js/quests/scraper.js

      - run: npm run bundle

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ ! env.ACT }}
        with:
          commit_message: dump latest game data

      - run: rsync -avh --delete --exclude='.git' --filter='dir-merge,- .gitignore' . $GROUP_IRONMEN_PATH
        if: ${{ env.ACT }}
